### ISSUE TITLE
Point shader instead of sphere shader for big point clouds?

### ISSUE THREAD

**Issue by tractatus** [nmwsharp/polyscope#119]
Hi,

Thanks a lot for making such a nice tool for developing different 3D algorithms and visualizing intermediate output!
Together with `geometry central` this is now my go-to tool for developing and testing new algorithms.

I have a lot of interest in using `polyscope` where both meshes and point clouds are the objects of interest in the same scene.

The handling of meshes is excellent but with very large point clouds the sphere shader seems to create some lag especially if working from a simple laptop system. I was wondering if there is any idea to enable an alternative point shader instead of spheres for such situations? Not sure exactly the best way to implement this while staying true to how you envision the PointCloud class to develop within Polyscope.

Maybe something along these lines using GLFW?:
https://github.com/TarcisioLOliveira/PointCloud

**Comment by nmwsharp** [comment]
Hi! Very glad to hear these tools are useful to you.

An "efficient" mode for point clouds has been on my TODO list for a long time. I hacked together an initial implementation in this branch: https://github.com/nmwsharp/polyscope/commits/point_render_opts. It adds an option `PointCloud::setPointRenderMode(PointRenderMode::Squares)`, which renders the points with cheap little quads instead of expensive spheres. On my machines, this scales well to millions of points.

Try it out and let me know if it works for you! If everything looks good I'll try to document it / writing python bindings / etc and get it in a new version before too long.

**Comment by tractatus** [comment]
This is great! Really awesome!
I will play around with it and try to document as much as possible with my own example point clouds if that would be useful for the docs.

**Comment by nmwsharp** [comment]
Documented here: https://polyscope.run/structures/point_cloud/basics/#point-render-mode (available in Python too)
