### ISSUE TITLE
performance optimization - use instancing when rendering point clouds

### ISSUE THREAD

**Issue by DanIsraelMalta** [nmwsharp/polyscope#120]
Point clouds rendering performance degrades exponentially as they increase in size. 
I believe that the cause for the performance degradation is not using instancing, i.e. - the renderer uses `glDrawArrays`/`glDrawElements` (which requires lots of draw calls) instead of `glDrawArraysInstanced`/`glDrawElementsInstanced`.

p.s. - great piece of software, very configurable and easily integrated as a debug viewer inside very complex software infrastructure.

edit - just noticed this issue #119

**Comment by DanIsraelMalta** [comment]
so, I thought that point clouds are rendered via instancing a predefined sphere mesh. I was wrong, just took a look in sphere shaders and found out it was drawn on a canvas.
that means that instancing will not be useful here (unless changing the point rendering process).

**Comment by nmwsharp** [comment]
I just added a comment on the linked issue #119 with a possible solution.

To quickly answer the cause, the issue is that the point shader uses "clever-but-expensive" ray-casting for each screen fragment of the point. Not only is this logic quite computation-heavy per-pixel, but it writes to the depth buffer, which disables important optimizations like Z-culling.

The solution is probably just to add an alternate shader which does away with the fancy spheres, and just renders points as little quads---see my comment in #119.
