### ISSUE TITLE
lengthScale calculation causing structures to disappear

### ISSUE THREAD

**Issue by weshoke** [nmwsharp/polyscope#150]
```
float Structure::lengthScale() {
  // compute the scaling caused by the object transform
  const glm::mat4x4& T = objectTransform.get();
  float transScale = (T[0][0] + T[1][1] + T[2][2]) / (3. * T[3][3]);
  return transScale * objectSpaceLengthScale;
}
```

I'm trying to understand what the above code is trying to achieve.  When the values in the numerator sum to a negative, the calculation in `updateStructureExtents` sets `state::lengthScale` to 0 since negatives are less than zero and the final lengthScale is set by `state::lengthScale = std::max(state::lengthScale, x.second->lengthScale());`.

When the numerator is positive, all of a sudden there's a jump in the lengthScale and 

```
if (state::lengthScale == 0) {
    state::lengthScale = glm::length(maxBbox - minBbox);
  }
```

is not triggered, causing the scene to suddenly disappear.

I know I can use `set_automatically_compute_scene_extents` to disable setting extents, but this behavior seems like a bug.  I'm seeing this when setting the transforms on SurfaceMesh objects explicitly.  For example:

```
[[ 0.          0.21110303  0.97746382  0.        ]
 [ 1.          0.          0.          0.        ]
 [ 0.          0.97746382 -0.21110303  0.        ]
 [ 0.          0.          0.          1.        ]]
```

versus:

```
[[ 0.         -0.08665152  0.99623868  0.        ]
 [ 1.          0.          0.          0.        ]
 [ 0.          0.99623868  0.08665152  0.        ]
 [ 0.          0.          0.          1.        ]]
```

Nothing here has changed regarding the extents of the scene yet the  lengthScale  changes dramatically and so does the bounding computation of the scene.

Is the goal here to accommodate a scaling factor in the structure transform to compute the overall bounds?

Doesn't `Structure::boundingBox()` already account for scaling?

**Comment by nmwsharp** [comment]
Yep, you're right, that code looks totally bogus. It should always compute a positive value. I think it was meant to be applied to a matrix split in to scale/rotation/translation components, but it certainly doesn't make sense to apply it directly to the diagonal elements of full transformation matrix.

More broadly the idea for distinguishing `lengthScale` from `boundingBox` was that since `lengthScale` is used to set visual properties like the radius of points etc, it might be useful to set it manually independently of the bound box.

Anyway, I'll try to put together a fix real quick (though it might be delayed a little cause of holiday stuff 🙂)

**Comment by nmwsharp** [comment]
Does this fix look sane? https://github.com/nmwsharp/polyscope/pull/151

**Comment by nmwsharp** [comment]
fixed now, thank you for reporting!
