### ISSUE TITLE
Mouse & keyboard ignored, Windows wsl2/vcxsrv 

### ISSUE THREAD

**Issue by Bathsheba** [nmwsharp/polyscope#162]
C++ novice here.  The demo app launches and the Polyscope window displays correctly; the framerate updates, it's definitely running.  But it won't interact, the controls don't receive mouse clicks or keypresses. With one exception: the mouse wheel works to zoom in and out.

Windows 10 Pro 21H2, wsl2 Ubuntu with VcXsrv.  Polyscope and demo-app compile clean.  xeyes and xcalc work and receive mouse and keyboard events.

I tried some different Mesa versions, no change:
[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 3.3 (Core Profile) Mesa 21.2.6
[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 3.3 (Core Profile) Mesa 22.0.0 - kisak-mesa PPA
[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 4.2 (Core Profile) Mesa 22.1.0-devel (git-b7fbaf9 2022-03-16 focal-oibaf-ppa)

At https://github.com/cmu-geometry/ddg-exercises-js/issues/1 it's suggested this problem may be due to compiler over-optimization.  I tried removing -O* flags throughout without result.

I was hoping to solve this without getting into either Visual Studio or Windows 11, but perhaps that is a vain hope.

Thanks for any suggestions, 
Bathsheba

$ glxinfo -B
name of display: 172.17.32.1:0
display: 172.17.32.1:0 screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
Vendor: Microsoft Corporation (0xffffffff)
Device: D3D12 (NVIDIA GeForce GTX 1070) (0xffffffff)
Version: 22.1.0
Accelerated: yes
Video memory: 24436MB
Unified memory: no
Preferred profile: core (0x1)
Max core profile version: 4.2
Max compat profile version: 4.2
Max GLES1 profile version: 1.1
Max GLES[23] profile version: 3.1
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce GTX 1070)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 22.1.0-devel (git-b7fbaf9 2022-03-16 focal-oibaf-ppa)
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.2 (Compatibility Profile) Mesa 22.1.0-devel (git-b7fbaf9 2022-03-16 focal-oibaf-ppa)
OpenGL shading language version string: 4.20
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 22.1.0-devel (git-b7fbaf9 2022-03-16 focal-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

**Comment by nmwsharp** [comment]
Hi! Thanks for the detailed report.

At the high-level these virtual/emulated/containerized environments can be huge headaches, and often graphics/openGL stuff just plain won't work in such a setup due to unsupported features. However in this case it seems that we actually extremely close! Everything is working on the openGL side, it is just that mouse inputs aren't being processed for some reason.

As a first answer, if you are just looking to get something working, this codebase should work just fine if you compile it directly in Windows (rather than in WSL), via Visual Studio or some other C++ compiler setup.

OK, that being said, the problem here is likely something related to [glfw](https://www.glfw.org/), which Polyscope uses internally to handle windowing/mouse events/etc. I'm happy to try a few steps to debug this one, but fair warning that there is a decent chance the actual issue is upstream in GLFW somewhere, in which case there is not much we can do to fix it.

One quick first try: could you try compiling the demo app from this branch https://github.com/nmwsharp/polyscope/commits/volumes_and_views2, and see if it works there? Most of the changes in that branch are irrelevant, but it has the GLFW dependency updated to the latest version. If we're lucky this has already been fixed upstream in GLFW! If you're switching branches, be sure the submodule gets updated properly (e.g. run `git submodule update --recursive` after changing the branch). I always mess that part up.

Also, if you're not already, could you compile in DEBUG mode? This will cause Polyscope to do some extra error checking which might give more info.

**Comment by nmwsharp** [comment]
Glad to hear it's working now! Thanks for following-up. I still have no idea what could be going on under the hood, but at least updating is a workaround.
