### ISSUE TITLE
Remove unused gtx/string_cast

### ISSUE THREAD

**Issue by Q-Minh** [nmwsharp/polyscope#185]
Hi, would it be possible to remove [this line](https://github.com/nmwsharp/polyscope/blob/master/deps/glm/glm/gtx/string_cast.hpp#L36)? I don't see the glm::to_string() function used in the code base, and every time I reconfigure my CMake project which uses polyscope, the preprocessor directive has to be commented out in order to compile my project which uses CUDA.

Thank you!

**Comment by nmwsharp** [comment]
Sure! Thanks for reporting. I've never compiled Polyscope in a CUDA codebase so I wouldn't know. As you say, it looks like `glm::to_string()` is unused.

Rather than modifying our copy of GLM, I've removed all imports of that file within Polyscope itself in #189. I think this should fix your issue. If it doesn't please reopen this!
