### ISSUE TITLE
CurveNetwork::updateNodePositions() do not update render position of edge cylinder

### ISSUE THREAD

**Issue by OkifuZ** [nmwsharp/polyscope#234]
as doc says
![image](https://github.com/nmwsharp/polyscope/assets/49850328/17689e9f-b0bd-4a1d-a7f3-d66da4fd73a4)

code like:
```c++
void main_loop() {
  for (size_t i = 0; i < nParticles; i++) {
	  nodes[i] += Vector3r{0.01, 0.01, 0.01};
  }
  if (curve_network) curve_network->updateNodePositions(nodes);
}
```
in user_callback function will only update curvenetwork's sphere position, but not cylinder:

https://github.com/nmwsharp/polyscope/assets/49850328/65ac245e-e14d-480a-aeed-d7bca1e641a3

however, adding `CurveNetwork::refresh()`, it's fine. 
```c++
if (curve_network) {
  curve_network->updateNodePositions(nodes);
  curve_network->refresh();
}
```
It seems that `edgeProgram.reset()` in the `refresh` function matters, what does `refresh` do? Not sure this to be a bug or do I miss something in the doc?

**Comment by nmwsharp** [comment]
Thanks for filing this! This is a bug, it should definitely work without the refresh.

In fact, I just fixed this bug in the `update_volume` branch! It was a problem with the way `ManagedBuffer`s get updated. You should be able to hop on that branch ASAP if you want the fix right now. Otherwise I am planning to merge it into master soon.

**Comment by nmwsharp** [comment]
fix has been merged for a while! if anyone sees this please reopen
