### ISSUE TITLE
UI 

### ISSUE THREAD

**Issue by matthijsramlab** [nmwsharp/polyscope#54]
Would it be possible to integrate a platform like QT python? I would like to add some buttons etc.

**Comment by nmwsharp** [comment]
In C++, we allow you to build a Dear ImGui UI via the [user callback](http://polyscope.run/features/user_callback/). However, this feature is not yet exposed in Python because I haven't figured out the right way to wrap ImGui. This is definitely on the roadmap, and will be the next major feature added to the Python bindings! Though I'm not sure yet when I'll have time.

As an aside, using QT specifically is very unlikely; it would require pretty fundamental changes to the way Polyscope is set up.
