### ISSUE TITLE
Taking screenshot not works properly

### ISSUE THREAD

**Issue by MasoudBNJ** [nmwsharp/polyscope#75]
When I press the screenshot button in polyscope screen, it saves image file in .tga format in the current directory. But when I open it with TGAViewer app, it is not what it really was on the screen and only captured some random shapes (or sometimes captured nothing!).

**What I see in the polyscope screen:**
![expected](https://user-images.githubusercontent.com/33718460/94915313-8878a180-04b9-11eb-9cf5-7666bdd9d7c2.png)
**And this is the result of the screenshot (it gives different results each time):**
![screenshot2](https://user-images.githubusercontent.com/33718460/94915467-d2fa1e00-04b9-11eb-8f70-054736f79214.png)
**For another shape:**
![screenshot](https://user-images.githubusercontent.com/33718460/94915774-56b40a80-04ba-11eb-9688-ec4a624f0dd8.png)

**Comment by nmwsharp** [comment]
Uh oh! This does seem like a bug.

I've run in to multiple issues before with `.tga` files not looking right. For instance, on my mac, they all appear upside down! Perhaps there is some issue with the `tga` file format I'm not understanding. [We simply use](https://github.com/nmwsharp/polyscope/blob/master/src/screenshot.cpp#L46) `stb_image` to write the `tga` files, and I doubt `stb_image` is broken... so I'm not really sure where the problem lies.

I think the solution will be to just change the default screenshot format to `png` in the next major release. It's slower, but everyone understands `png` better anyway :) For now, a workaround is to manually call `screenshot()` and set the file name to some other extension.

**Comment by MasoudBNJ** [comment]
Thank you for your reply!
Yes, it seems a bug with .tga format because when I used `polyscope.screenshot('a.png')`, it worked like a charm :)

**Comment by nmwsharp** [comment]
Default screenshot format changed to .png in 616d459b4d741c93305115c295cdf46703ae157e.

Hopefully this resolves issues!
