### ISSUE TITLE
Crash in GLShaderProgram::setUniform when using "Select Vertex" due to mesh edges not enabled (u_edgeWidth nonexistent).

### ISSUE THREAD

**Issue by TriazoneZero** [nmwsharp/polyscope#90]
If I use "Select Vertex" on a surface mesh I get an exception in GLShaderProgram::setUniform  whenever "Edges" are not enabled.
This is due to u_edgeWidth is not found as a uniform, and an exception is thrown in gl_engine.cpp l.915 because u_edgeWidth uniform is nonexistent:

```c++
// Set a double --- WARNING casts down to float
void GLShaderProgram::setUniform(std::string name, double val) {
  glUseProgram(programHandle);

...

  throw std::invalid_argument("Tried to set nonexistent uniform with name " + name);
}
```

Problem seems to lie in surface_mesh.cpp l.877
What I did you get around it is

```diff
long long int SurfaceMesh::selectVertex() {

  // Make sure we can see edges
- edgeWidth = 1.0;
+ this->setEdgeWidth(1.);
 this->setEnabled(true);

 long long int returnVertInd = -1;
...
```

**Comment by nmwsharp** [comment]
Ah! Thanks for reporting, you're exactly right. This bug was introduced in some recent changes.

Should be fixed in 32dad097b5d1a031154988629b0c90a9a305dea4. Also, 107ab7efc1018b6257c317e41a72c499bf4e7d79 fixes an unrelated bug in which calling `selectVertex()` before calling `show()` for the first time would hang without actually displaying the GUI.

Please reopen if you still see any issues.
