### ISSUE TITLE
Transformation Gizmo throws on Failure to Find Normal Attribute

### ISSUE THREAD

**Issue by mgsutton** [nmwsharp/polyscope#98]
When trying to use the transformation gizmo on a surface mesh, it throws an exception within `GLShaderProgram::setDataLocations()` complaining about the inability to find a normal attribute.  I've tried debugging on my end, but I'm weak on shader programming, so I'm not sure what the issue might be.  OS is Windows 10 Pro x64.

**Comment by nmwsharp** [comment]
Hi!

Can you confirm that the issue persists on the current main branch? This commit https://github.com/nmwsharp/polyscope/commit/ddc4c0604ca78ec78bdb92423322a9a271743db5 fixed an issue that sound very similar.

For context, the cause of these issues is usually that on some platform openGL optimizes away an attribute that is not being used, so then when we got to set the attribute there is no where to set it and we throw an error. Some more care in our openGL wrapper could probably handle the situation better... in practice my fix usually to change the shader so that the variable no longer gets optimized away.

**Comment by mgsutton** [comment]
Woops!  That was it.  https://github.com/nmwsharp/polyscope/commit/ddc4c0604ca78ec78bdb92423322a9a271743db5 seems to have fixed the issue.  Sorry for the noise.

**Comment by nmwsharp** [comment]
no worries, glad its fixed!
